window.sentences = [
  "i could not find shelter anywhere",
  "i have to keep moving",
  "behind me",
  "thousands of moaning souls",
  "it was chaos",
  "i was with my boyfriend",
  "when i saw it for the first time",
  "it was not fast or slow", 
  "just steadfast",
  "no one seemed to notice after the first scream",
  "a zombie screeched a kid",
  "shut your mouth replied the mother",
  "and then it happened",
  "chaos",
  "i left the mall holding my boyfriend's hand",
  "just his hand",
  "shit they are right behind me",
  "got to find shelter soon",
  "i haven't got many supplies",
  "i don't know how long I can hold out like this",
  "just keep running",
  "type for your life"
];
